version: '3'
services:

  vscsync:
    image: ${DOCKERHUB_USERNAME}/vscsync:latest
    build:
      context: ./
      dockerfile: ./vscoffline/vscsync/Dockerfile
    dns:
      - 1.1.1.1
    volumes:
      - ./artifacts/:/artifacts/:U
    environment:
      - SYNCARGS=--sync
      # Enable to sync all extensions
      #- SYNCARGS=--syncall
      # Enable a logfile
      #- SYNCARGS=--sync --logfile /logs/sync.log

  vscgallery:
    image: ${DOCKERHUB_USERNAME}/vscgallery:latest
    build:
      context: ./
      dockerfile: ./vscoffline/vscgallery/Dockerfile
    volumes:
      - ./artifacts/:/artifacts/
      # Enable for custom SSL certs
      #- ./vscoffline/vscgallery/ssl/:/opt/vscoffline/vscgallery/ssl # Enable for custom SSL certs
      # Enable to store logfiles in its own folder
      # ./logs/:/logs/
    ports:
      - 9443:9443
    environment:
      - BIND=0.0.0.0:9443
