version: '3'
services:

  vscsync:
    image: lolinternet/vscsync:latest
    build:
      context: ./
      dockerfile: ./vscoffline/vscsync/Dockerfile
    dns:
      - 1.1.1.1
    volumes:
      #- ./vscoffline/:/opt/vscoffline/:ro # Enable for dev
      - ./artifacts/:/artifacts/
    environment:
      - SYNCARGS=--go
      #- SYNCARGS=--goall # Enable to get all extensions

  vscgallery:
    image: lolinternet/vscgallery:latest
    build:
      context: ./
      dockerfile: ./vscoffline/vscgallery/Dockerfile    
    volumes:
      #- ./vscoffline/:/opt/vscoffline/:ro # Enable for dev
      - ./artifacts/:/artifacts/
      #- ./vscoffline/vscgallery/ssl/:/opt/vscoffline/vscgallery/ssl # Enable for custom SSL certs
    ports:
      - 443:443
    environment:
      - BIND=0.0.0.0:443