name: Push to Github Container Registry

on:
  push:
    branches:
      - 'main'
  release:
    types: [edited, released]

env:
  REGISTRY: ghcr.io
  GH_TOKEN: ${{ github.token }}

jobs:
  ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GHCR
        uses: docker/login-action@v3 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for sync
        id: sync
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/vscsync

      - name: Extract metadata (tags, labels) for Gallery
        id: gallery
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/vscgallery

      - name: Show metadata
        run: |
          echo "Registry: ${{ env.REGISTRY }}"
          echo "SyncVersion: ${{ steps.sync.outputs.version }}"
          echo "Sync Tags: ${{ steps.sync.outputs.tags }}"
          echo "Sync Labels: ${{ steps.sync.outputs.labels }}"
          echo "Gallery Version: ${{ steps.gallery.outputs.version }}"
          echo "Gallery Tags: ${{ steps.gallery.outputs.tags }}"
          echo "Gallery Labels: ${{ steps.gallery.outputs.labels }}"

      - name: Sync - Build and push
        id: docker_build_sync
        uses: docker/build-push-action@v6
        with:
          file: ./vscoffline/vscsync/Dockerfile          
          tags: ${{ steps.sync.outputs.tags }}
          labels: ${{ steps.sync.outputs.labels }}
          push: true
          
      - name: Gallery - Build and push
        id: docker_build_gallery
        uses: docker/build-push-action@v6
        with:
          file: ./vscoffline/vscgallery/Dockerfile
          tags: ${{ steps.gallery.outputs.tags }}
          labels: ${{ steps.gallery.outputs.labels }}
          push: true

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}//${{ github.repository }}/vscsync
          subject-digest: ${{ steps.docker_build_sync.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository }}/vscgallery
          subject-digest: ${{ steps.docker_build_gallery.outputs.digest }}
          push-to-registry: true